# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Acli < Formula
  desc "Manage content in multi platforms."
  homepage "https://github.com/k8scat/articli"
  version "0.5.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/k8scat/articli/releases/download/v0.5.2/acli-darwin-arm64.tar.gz"
      sha256 "07b6194f3f2ebd90499382ed324619dcfd01b3fe0ad58565e55a179c7be0445e"

      def install
        bin.install "acli"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/acli", "completion", "bash")
        (bash_completion/"acli").write output
        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/acli", "completion", "zsh")
        (zsh_completion/"_acli").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/k8scat/articli/releases/download/v0.5.2/acli-darwin-amd64.tar.gz"
      sha256 "8d68c1977d089d7f01f2b934dbb1ff045583e09f3fefc9f8686f1adab82e8a55"

      def install
        bin.install "acli"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/acli", "completion", "bash")
        (bash_completion/"acli").write output
        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/acli", "completion", "zsh")
        (zsh_completion/"_acli").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/k8scat/articli/releases/download/v0.5.2/acli-linux-amd64.tar.gz"
      sha256 "685f36299176f7b8bad5f3067fcb8c5108d9cb80bdac3bcfb8d92ba0c9452f26"

      def install
        bin.install "acli"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/acli", "completion", "bash")
        (bash_completion/"acli").write output
        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/acli", "completion", "zsh")
        (zsh_completion/"_acli").write output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/k8scat/articli/releases/download/v0.5.2/acli-linux-arm64.tar.gz"
      sha256 "aa08c3e5d16dffda74c32d03c33d93043b0e1b56514537761bce4d6324602e0c"

      def install
        bin.install "acli"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/acli", "completion", "bash")
        (bash_completion/"acli").write output
        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/acli", "completion", "zsh")
        (zsh_completion/"_acli").write output
      end
    end
  end

  depends_on "git"

  test do
    system "#{bin}/acli version"
  end
end
