# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Acli < Formula
  desc "Manage content in multi platforms."
  homepage "https://github.com/k8scat/articli"
  version "0.6.7"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/k8scat/articli/releases/download/v0.6.7/articli_0.6.7_darwin_arm64.tar.gz"
      sha256 "994d1e2f2e2e5ce449f887b333157b5f76309ad9f4014b74aad89f411c0db3f5"

      def install
        bin.install "acli"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/acli", "completion", "bash")
        (bash_completion/"acli").write output
        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/acli", "completion", "zsh")
        (zsh_completion/"_acli").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/k8scat/articli/releases/download/v0.6.7/articli_0.6.7_darwin_amd64.tar.gz"
      sha256 "e7d1afb12f721d6d4b73ce14aa395600c3db228c27068d200efce86c53f7c827"

      def install
        bin.install "acli"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/acli", "completion", "bash")
        (bash_completion/"acli").write output
        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/acli", "completion", "zsh")
        (zsh_completion/"_acli").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/k8scat/articli/releases/download/v0.6.7/articli_0.6.7_linux_arm64.tar.gz"
      sha256 "2cb16528ea2d3d73c001d483fe6941e25e9597ddaa9def8f5dce97cf808bf127"

      def install
        bin.install "acli"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/acli", "completion", "bash")
        (bash_completion/"acli").write output
        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/acli", "completion", "zsh")
        (zsh_completion/"_acli").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/k8scat/articli/releases/download/v0.6.7/articli_0.6.7_linux_amd64.tar.gz"
      sha256 "1d8f6f38e2516d6a7040cf23c5f3c1227dd2c0678364b5d7294c35f2eaa953a7"

      def install
        bin.install "acli"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/acli", "completion", "bash")
        (bash_completion/"acli").write output
        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/acli", "completion", "zsh")
        (zsh_completion/"_acli").write output
      end
    end
  end

  test do
    system "#{bin}/acli version"
  end
end
