# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Acli < Formula
  desc "Manage articles in multi platforms."
  homepage "https://github.com/k8scat/articli"
  version "0.1.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/k8scat/articli/releases/download/v0.1.5/acli-darwin-amd64.tar.gz"
      sha256 "5dd26850299ec4a61998a6af06b0cb58155718e7640c08f946a49d3aef6dca9e"

      def install
        bin.install "acli"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/acli", "completion", "bash")
        (bash_completion/"acli").write output
        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/acli", "completion", "zsh")
        (zsh_completion/"_acli").write output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/k8scat/articli/releases/download/v0.1.5/acli-darwin-arm64.tar.gz"
      sha256 "452d1850bb34243d318e9cc8f54cb84b67f637add8fe3ec80836e28014e8c42e"

      def install
        bin.install "acli"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/acli", "completion", "bash")
        (bash_completion/"acli").write output
        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/acli", "completion", "zsh")
        (zsh_completion/"_acli").write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/k8scat/articli/releases/download/v0.1.5/acli-linux-arm64.tar.gz"
      sha256 "f89ce612c40d4ee1ffd15c9444bb5105aa73154b51547cd20bf8dcbb3dc534a3"

      def install
        bin.install "acli"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/acli", "completion", "bash")
        (bash_completion/"acli").write output
        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/acli", "completion", "zsh")
        (zsh_completion/"_acli").write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/k8scat/articli/releases/download/v0.1.5/acli-linux-amd64.tar.gz"
      sha256 "f0a9a20b502ac268960137b5366586c2d3760df5cdb3939bd7cb3dcaa3543da7"

      def install
        bin.install "acli"
        # Install bash completion
        output = Utils.safe_popen_read("#{bin}/acli", "completion", "bash")
        (bash_completion/"acli").write output
        # Install zsh completion
        output = Utils.safe_popen_read("#{bin}/acli", "completion", "zsh")
        (zsh_completion/"_acli").write output
      end
    end
  end

  depends_on "git"

  test do
    system "#{bin}/acli version"
  end
end
